backlog/urls.py
""" 
backlog/urls.py - maps url patterns to views 
"""
from django.conf.urls import patterns, url

from backlog import views

urlpatterns = patterns('',
    # UserStory Views
    # VIEW                TEMPLATE                        URL PATTERN
    # --------------------------------------------------------------------
    # IndexView           index.html                      /backlog/
    # DetailView          detail.html                     /backlog/<id>
    # UserStoryCreate     userstory_form.html             /backlog/add/
    # UserStoryUpdate     userstory_edit.html             /backlog/edit/<id>
    # UserStoryDelete     userstory_confirm_delete.html   /backlog/delete/<id>
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^add/$', views.UserStoryCreate.as_view(), name='userstory_add'),
    url(r'^edit/(?P<pk>\d+)/$', views.UserStoryUpdate.as_view(), name='userstory_edit'),
    url(r'^delete/(?P<pk>\d+)/$', views.UserStoryDelete.as_view(), name='userstory_delete'),
    
    # SprintBacklogView   sprint_backlog.html             /backlog/sprint/
    url(r'^sprint/$', views.SprintBacklogView.as_view(), name='sprint_backlog'),
    
    # Chart View
    #                                                     /backlog/chart/
    url(r'^sprint/chart/$', views.image_burndown_chart, name='chart'),
    
    # TimeRecord Views
    # VIEW                TEMPLATE                        URL PATTERN
    # --------------------------------------------------------------------
    # TimeRecordList      timerecords_list.html           /backlog/time/
    # TimeRecordView      time_record.html                /backlog/time/<id>
    # TimeRecordCreate    timerecord_form.html            /backlog/time/add/
    # TimeRecordUpdate    edit_time_record.html           /backlog/time/edit/<id>
    # TimeRecordDelete    timerecord_confirm_delete.html  /backlog/time/delete/<id>
    url(r'^time/$', views.TimeRecordList.as_view(), name='timerecords_list'),
    url(r'^time/(?P<pk>\d+)/$', views.TimeRecordView.as_view(), name='time_record'),
    url(r'^time/add/$', views.TimeRecordCreate.as_view(), name='time_record_add'),
    url(r'^time/edit/(?P<pk>\d+)/$', views.TimeRecordUpdate.as_view(), name='time_record_edit'),
    url(r'^time/delete/(?P<pk>\d+)/$', views.TimeRecordDelete.as_view(), name='time_record_delete'),
        
    # Sprint views 
    # VIEW                TEMPLATE                    URL PATTERN
    # --------------------------------------------------------------------
    # SprintListView      sprint_list.html            /backlog/settings/
    # SprintDetailView    settings.html               /backlog/settings/<id>/
    # SprintCreateView    sprint_form.html            /backlog/settings/add/
    # SprintUpdateView    sprint_edit.html            /backlog/settings/edit/<id>
    # SprintDeleteView    sprint_confirm_delete.html  /backlog/delete/<id>
    url(r'^settings/$', views.SprintListView.as_view(), name='settings'),
    url(r'^settings/(?P<pk>\d+)/$', views.SprintDetailView.as_view(), name='view_sprint'),
    url(r'^settings/add/$', views.SprintCreateView.as_view(), name='create_sprint'),
    url(r'^settings/edit/(?P<pk>\d+)/$', views.SprintUpdateView.as_view(), name='sprint_edit'),
    url(r'^settings/delete/(?P<pk>\d+)/$', views.SprintDeleteView.as_view(), name='sprint_delete'),
)

djangoproj/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'djangoproj.views.index', name='index'),
    url(r'^backlog/', include('backlog.urls', namespace="backlog")),
    # url(r'^$', )
    url(r'^admin/', include(admin.site.urls)),
)

djangoproj/views.py
from django.http import HttpResponse
from django.shortcuts import render_to_response

def index(request): 
    return render_to_response('index.html')

djangoproj/templates/base_site.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'backlog/style.css' %}" />
    <title>{% block title %}Project Huddle{% endblock %}</title>
</head>

<body>

<div id="head-container">
	<div id="header">
		<h1>
			Project Huddle 
		</h1>
	</div>
</div>
<div id="navigation-container">
	<div id="navigation">
		<ul>
			<li><a href="{% url 'index' %}">Home</a></li>
			<li><a href="{% url 'backlog:index' %}">Backlog</a></li>
			<li><a href="{% url 'backlog:sprint' %}">Sprint</a></li>
			<li><a href="{% url 'backlog:settings' %}">Settings</a></li>
		</ul>
	</div>
</div>
<div id="content-container">
	<div id="content-container2">
		<div id="content-container3">
			<div id="content">

		{% block content %}
		
		{% endblock %}
			
			</div>
			<div id="aside">
			{% block sidebar %}
				<h3>
					Product Vision: 
				</h3>
				<p>
					Project Huddle is an agile project management application
					that helps scrum teams keep track of projects.  In agile project
					management User Stories are descriptions of project requrements 
					broken down into manageable parts that help the team plan their
					project. This tool tracks lists of user stories and estimated
					time it takes to complete each story. Actual time spent can also
					be tracked.  The time is presented in a burndown chart 
					to help the team know if their goals are being reached or
					if adjustments need to be made.
				</p>
			{% endblock %}
			</div>
		</div>
	</div>
	<div id="footer-container">
		<div id="footer">
			Copyright © Project Huddle, 2014
		</div>
	</div>
</div>

djangoproj/templates/index.html
{% extends "base.html" %}

{% block title %}Project Huddle {% endblock %}

{% block content %}
				<h2>
					Python Project
				</h2>

<h3>Libraries Used</h3>
<h4>Django</h4>
<p>
Django is a web framework.
</p>
<h4>Report Lab</h4>
<p>
Report Lab was used to create the burndown chart.	
</p>

<h3>Features</h3>
<p>
Users can ceate User stories and update estimated and actual time for each story. A user story can be added to the current sprint (only one sprint is supported). Length of sprint can be 1 to 4 weeks.	
</p>

<h3>Files:</h3>
<p>The important files to look at are <br />
	backlog/<br />
	&nbsp; &nbsp; &nbsp; models.py<br />
	&nbsp; &nbsp; &nbsp; views.py<br />
	&nbsp; &nbsp; &nbsp; urls.py<br />
	&nbsp; &nbsp; &nbsp; charts.py<br />
</p>

<p>All files: </p>
<ul>
	<li>manage.py </li>
	<li>Procfile</li>
	<li>requirements.txt - lists package requirements</li>
	<li>runtime.txt - lists version of python to use</li>

in order to modularize a site, different functions can be made as apps inside a stie

this is the site:
<li>djangoproj/</li>
	<ul>
		<li>settings.py - django settings </li>
		<li>urls.py </li>
		<li>views.py  </li>
		<li>(wsgi.py) - config file </li>

		<li>templates/ </li>
		<ul> 
			<li>base_site.html</li>
			<li>index.html</li>
		</ul>
this is the app, there can be more than one app in a site, I only have one

<li>backlog/ </li>
	<ul>
		<li>urls.py </li>
		<li>models.py </li>
		<li>views.py </li>
		<li>charts.py </li>

		<li>(admin.py) - I did not use the django admin features </li>
		<li>(tests.py) - optional and not used by me. This is used to run tests on the application, an excellent feature! djangoproject.com has a nice tutorial on
test driven development that opened my eyes! but I ran out of time :-/ and did not do </li>

		<li>templates/ </li>
			<ul>
				<li>base.html </li>
				<li>backlog/ </li>
				<ul>
					# user story views templates
					<li>index.html </li>
					<li>detail.html </li>
					<li>userstory_form.html </li>
					<li>userstory_edit.html </li>
					<li>userstory_confirm_delete.html </li>
					<li>sprint_backlog.html </li>
			
					# time records views templates
					<li>timerecords_list.html </li>
					<li>time_record.html </li>
					<li>timerecord_form.html </li>
					<li>edit_time_record.html </li>
					<li>timerecord_confirm_delete.html </li>

						# sprint views templates
					<li>sprint_list.html </li>
					<li>settings.html </li>
					<li>sprint_form.html </li>
					<li>sprint_edit.html </li>
					<li>sprint_confirm_delete.html </li>
				</ul>
			</ul>

		<li>static/ </li>
			<ul>
				<li>backlog/ </li>
				<li>style.css </li>
				<li>images/ </li>
				<ul>
					<li>backround.png </li>
				</ul>
			</ul>
				
	</ul>
</ul>

<h3>Other</h3>
<p>I used Heroku to host the application and the postgres database.</p>
<p>I used Git version control program, Heroku uses git to deploy apps.</p>

<h3>Problems, room for improvement</h3>
<p>After creating time records, the view should return to the user story to 
	which the time record belongs, instead of the detail view</p>
<p>Not very user friendly, user may not know where to start and how to 
	navigate through the program </p>
<p>The user must enter estimated hours for the whole sprint, for each day, 
this is not automatically carried through the days as it probably should, until the
user story has been completed </p>
{% endblock %}