backlog/urls.py
""" 
backlog/urls.py - maps url patterns to views 
"""
from django.conf.urls import patterns, url

from backlog import views

urlpatterns = patterns('',
    # UserStory Views
    # VIEW                TEMPLATE                        URL PATTERN
    # --------------------------------------------------------------------
    # IndexView           index.html                      /backlog/
    # DetailView          detail.html                     /backlog/<id>
    # UserStoryCreate     userstory_form.html             /backlog/add/
    # UserStoryUpdate     userstory_edit.html             /backlog/edit/<id>
    # UserStoryDelete     userstory_confirm_delete.html   /backlog/delete/<id>
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^add/$', views.UserStoryCreate.as_view(), name='userstory_add'),
    url(r'^edit/(?P<pk>\d+)/$', views.UserStoryUpdate.as_view(), name='userstory_edit'),
    url(r'^delete/(?P<pk>\d+)/$', views.UserStoryDelete.as_view(), name='userstory_delete'),
    
    # SprintBacklogView   sprint_backlog.html             /backlog/sprint/
    url(r'^sprint/$', views.SprintBacklogView.as_view(), name='sprint_backlog'),
    
    # Chart View
    #                                                     /backlog/chart/
    url(r'^sprint/chart/$', views.image_burndown_chart, name='chart'),
    
    # TimeRecord Views
    # VIEW                TEMPLATE                        URL PATTERN
    # --------------------------------------------------------------------
    # TimeRecordList      timerecords_list.html           /backlog/time/
    # TimeRecordView      time_record.html                /backlog/time/<id>
    # TimeRecordCreate    timerecord_form.html            /backlog/time/add/
    # TimeRecordUpdate    edit_time_record.html           /backlog/time/edit/<id>
    # TimeRecordDelete    timerecord_confirm_delete.html  /backlog/time/delete/<id>
    url(r'^time/$', views.TimeRecordList.as_view(), name='timerecords_list'),
    url(r'^time/(?P<pk>\d+)/$', views.TimeRecordView.as_view(), name='time_record'),
    url(r'^time/add/$', views.TimeRecordCreate.as_view(), name='time_record_add'),
    url(r'^time/edit/(?P<pk>\d+)/$', views.TimeRecordUpdate.as_view(), name='time_record_edit'),
    url(r'^time/delete/(?P<pk>\d+)/$', views.TimeRecordDelete.as_view(), name='time_record_delete'),
        
    # Sprint views 
    # VIEW                TEMPLATE                    URL PATTERN
    # --------------------------------------------------------------------
    # SprintListView      sprint_list.html            /backlog/settings/
    # SprintDetailView    settings.html               /backlog/settings/<id>/
    # SprintCreateView    sprint_form.html            /backlog/settings/add/
    # SprintUpdateView    sprint_edit.html            /backlog/settings/edit/<id>
    # SprintDeleteView    sprint_confirm_delete.html  /backlog/delete/<id>
    url(r'^settings/$', views.SprintListView.as_view(), name='settings'),
    url(r'^settings/(?P<pk>\d+)/$', views.SprintDetailView.as_view(), name='view_sprint'),
    url(r'^settings/add/$', views.SprintCreateView.as_view(), name='create_sprint'),
    url(r'^settings/edit/(?P<pk>\d+)/$', views.SprintUpdateView.as_view(), name='sprint_edit'),
    url(r'^settings/delete/(?P<pk>\d+)/$', views.SprintDeleteView.as_view(), name='sprint_delete'),
)

djangoproj/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'djangoproj.views.index', name='index'),
    url(r'^backlog/', include('backlog.urls', namespace="backlog")),
    # url(r'^$', )
    url(r'^admin/', include(admin.site.urls)),
)

backlog/models.py
# backlog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from datetime import date, timedelta
from django.db import IntegrityError


class UserStory(models.Model):
    """
    UserStory Model class: User stories are objects that are
    saved in database.
    """
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=500, default="As a <user/persona> \
        I want to <take this action> so that <I get this result>")
    validation = models.CharField(max_length=200, default="When I <take this action>, \
        <this happens>")
    
    SCORE_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (5, '5'),
        (8, '8'),
        (13, '13'),
        (21, '21'),
        (34, '34'),
        (55, '55'),
        (89, '89'), 
        (144, '144'),
    )
    
    value = models.IntegerField(choices=SCORE_CHOICES, default=0)
    effort = models.IntegerField(choices=SCORE_CHOICES, default=1)   
    
    STATUS_CHOICES = (
        ('B', 'Backlog'),        #In Backlog, not begun
        ('S', 'Sprint'),         #In sprint, not begun
        ('P', 'In Progress'),   
        ('I', 'Integrate'),      
        ('D', 'Document'),
        ('T', 'Test'),
        ('C', 'Complete'),
        ('A', 'Accepted'),
    )
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='B')
    
    submitted_by = models.ForeignKey(User, related_name="submitter")
    assigned_to = models.ForeignKey(User, related_name="developer", null=True)
    
    in_sprint = models.BooleanField(default=False)
    
    def relative_priority(self):
        return self.value / self.effort
    
    # returns a srting that identifies the object
    def __str__(self):
        return self.title
    
    # returns the default url of object, detail view in this case
    def get_absolute_url(self):
        return reverse('backlog:detail', kwargs={'pk': self.pk})



class TimeRecord(models.Model):
    """
    TimeRecord model - TimeRecord objects are records in the database
    that have a user story as a foreign key. One user story may have 
    many TimeRecords. A time record only belongs to one user story.
    Provides a record of work acutal and estimated hours
    This data is used to create the burndown chart
    """
    actual_time = models.IntegerField(default=0, help_text="Time in hours") 
    estimated_time = models.IntegerField(default=0, help_text="Time in hours")
    user_story = models.ForeignKey(UserStory)
    day = models.DateField(help_text="eg. '2014-03-17'")
    
    #there should only be one record per user story per day
    class Meta:
        unique_together = (("user_story", "day"),)
    
    #string that identifies a time record (eg '2013-03-17 - User Story Title' )
    def __str__(self):
            return str(self.day) + " - " + self.user_story
    
    #default url for object, the detail view of the object
    def get_absolute_url(self):
            return reverse('backlog:time_record', kwargs={'pk': self.pk})
        
        
        
class TrackHours(models.Model):
    """ 
    total actual and estimated hours by day
    """
    day_of_sprint = models.IntegerField(default=1, primary_key=True)
    total_estimated_hours = models.IntegerField(default=0)
    total_actual_hours = models.IntegerField(default=0)
    
    def get_est_point(self):
        est_point = (self.day_of_sprint, self.total_estimated_hours)
        return est_point
    
    def get_act_point(self):
        act_point = (self.day_of_sprint, self.total_actual_hours)
        return act_point
        
        

class Sprint(models.Model):
    """ 
    Sprint Model Class: the application must have only one sprint object defined.
    In the future, support multiple (future and past) sprints.
    """
    CHOICES = (
        (7, '1 Week'),
        (14, '2 Weeks'),
        (21, '3 Weeks'),
        (28, '4 Weeks'),
    )
    
    #length in days of sprint.
    sprint_days = models.IntegerField(choices=CHOICES, default=14)
    start_date = models.DateField(help_text="eg. '2014-03-17'")
    #number of developers that work on project
    num_dev = models.IntegerField(default=1) 
    
    def productive_hours(self):
        productive_hours = self.num_dev * 35  #assuming 40 hour work week
                                                #change this to be custimizable
        return productive_hours
    
    
    def update_time_sum(self):
        """ 
        Creates a table in DB of record of daily sum of hours 
        does not return a value, updates database
        """
        #loop for each day in sprint
        for day in range(self.sprint_days):
            
            date = self.start_date + timedelta(days=day)
            #get all the time records for each day of sprint
            day_records = TimeRecord.objects.filter(user_story__in_sprint=True,day=str(date))
            
            tot_est = 0
            tot_act = 0
            #for all of the records for each day add up the totals
            for record in day_records:
                tot_est = tot_est + record.estimated_time
                tot_act = tot_act + record.actual_time
                
            #create a record for each day of sprint
            try:
               TrackHours.objects.create(day_of_sprint=day,
                        total_estimated_hours=tot_est, total_actual_hours=tot_act)
            #or if a record for each day already exists, update it
            except IntegrityError:
                item = TrackHours.objects.get(day_of_sprint=day)
                item.total_estimated_hours=tot_est
                item.total_actual_hours=tot_act
                item.save()


    def get_data(self):
        """
        sprint_object.get_data() - Sprint class method
        returns a list of tuples that hold data points for each line to plot
        ie data = [ (line data), (line data)]
        where line data = (x1, y1), (x2, y2), ... etc
        returns data for two lines: estimated and actual hours (date, hours)
        dets data from TrackHours database table
        """
        #get all TrackHours records, each record has data for both lines to plot
        daily_data = TrackHours.objects.all()
        
        line_est = []   #will hold a list of points for estimated work left
        line_act = []   #will hold a list of points for work actually done
        for points in daily_data:
            line_est.append(points.get_est_point())   #add a data point for each day
            line_act.append(points.get_act_point())   #add a data point for each day
        #make each line list into a tuple
        line_est = tuple(line_est)
        line_act = tuple(line_act)
        
        #pack up data to send to chart
        data = []
        data.append(line_est)
        data.append(line_act)
        
        return data
    
    #identifies each Sprint object, returns a string
    def __str__(self):
            return str(self.start_date)
    
    #maps object to a url, in this case the detail view of the object
    def get_absolute_url(self):
            return reverse('backlog:view_sprint', kwargs={'pk': self.pk})

backlog/views.py
# backlog/views.py
from django.shortcuts import render, render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy, reverse
from django.forms.models import inlineformset_factory

from backlog.charts import BurndownChart
from backlog.models import UserStory, TimeRecord, TrackHours, Sprint


"""
five UserStory views:
    1 - IndexView - displays a list of all user stories
    2 - DetailVeiw - displays all of the attributes of a UserStory object
                and a list of TimeRecords that have that UserStory as a 
                foreign key
    3 - UserStoryCreate - displays a form to create a new user story
                saves it to the database, and displays its DetailView on success
    4 - UserStoryUpdate - displays a form to modify an existing user story, 
                savies it to the database, and displays its DetailView on success
    5 - UserStoryDelete - displays a confirm form, deletes record from database
                and displays IndexView on success
"""
class IndexView(generic.ListView):
    model = UserStory
    template_name = 'backlog/index.html'
    context_object_name = 'backlog_list'

class DetailView(generic.DetailView):
    model = UserStory
    template_name = 'backlog/detail.html'
    
    def get_context_data(self, **kwargs):
        # call the base implementation
        context = super(DetailView, self).get_context_data(**kwargs)
        # add in a query set of time records
        #userstory = get_object_or_404(UserStory, title__iexact=self.args[0])
        userstory = context['object']
        context['time_records'] = TimeRecord.objects.filter(user_story=userstory)
        return context
    
class UserStoryCreate(CreateView):
    model = UserStory
    fields = ['title', 'description', 'validation', 'value', 'effort', 'assigned_to']
    
    def form_valid(self, form):
        form.instance.submitted_by = self.request.user
        return super(UserStoryCreate, self).form_valid(form)
    
class UserStoryUpdate(UpdateView):
    model = UserStory
    fields = ['title', 'description', 'validation', 'value', 'effort', 'assigned_to',
            'status', 'in_sprint']
    template_name_suffix = '_edit'

class UserStoryDelete(DeleteView):
    model = UserStory
    success_url = reverse_lazy('backlog:index')
    

"""
TIME RECORD VIEWS - there are 5 views
    1 - TimeRecordList - a list of all time records in database
    2 - TimeRecordVeiw - a detail view of one TimeRecord object
    3 - TimeRecordCreate - a form to submit, save a new TimeRecord
    4 - TimeRecordUpdate - a form to submit, save updates to existing TimeRecord
    5 - TimeRecordDelete - a form to delete an existing TimeRecord
"""
class TimeRecordList(generic.ListView):
    """ Shows a list of all time records """
    model = TimeRecord
    template_name = 'backlog/timerecords_list.html'
    context_object_name = 'time_records'

class TimeRecordView(generic.DetailView):
    """ shows a single time record """
    model = TimeRecord
    template_name = 'backlog/time_record.html'
    
class TimeRecordCreate(CreateView):
    model = TimeRecord
    fields = ['actual_time', 'estimated_time', 'user_story', 'day']
    
class TimeRecordUpdate(UpdateView):
    model = TimeRecord
    fields = ['actual_time', 'estimated_time', 'user_story', 'day']
    template_name = 'backlog/edit_time_record.html'

class TimeRecordDelete(DeleteView):
    model = TimeRecord
    success_url = reverse_lazy('backlog:hours_records')



#def submit(request, us_id):
#    us = get_object_or_404(UserStory, pk=us_id)

class SprintBacklogView(generic.ListView):
    """
    Shows a list of user stories that belong to the sprint
    """
    template_name = 'backlog/sprint_backlog.html'
    context_object_name = 'sprint_backlog'
    # queries user story objects that belong in the sprint
    queryset = UserStory.objects.filter(in_sprint=True)


def image_burndown_chart(request):
    """
    returns generated image of burndown chart
    """
    current_sprint = Sprint.objects.all()[0]
    
    current_sprint.update_time_sum()  #sum up hours

    chart = BurndownChart()
    image = chart.draw_chart(current_sprint.get_data(), 
                             current_sprint.sprint_days, 
                             current_sprint.productive_hours())
    image_data = image.asString('png')
    return HttpResponse(image_data, 'image/png')
    
    
"""
There are 5 views associated with the 
Sprint model:
    List - lists all sprint objects
    Detail - displays all of the attributes for a particular 
        sprint object
    Create - displays a form, submits data, creates new object
        saves a record in database, redirects to detail view upon 
        successful creation
    Update - displays a form, submits data, updates record in 
        database, redirects to detail view upon success
    Delete - displays confirm prompt, deletes record from database, 
        displays list view upon success.
"""
class SprintListView(generic.ListView):
    model = Sprint
    template_name = 'backlog/sprint_list.html'
    
class SprintDetailView(generic.DetailView):
    model = Sprint
    template_name = 'backlog/settings.html'
    
class SprintCreateView(CreateView):
    model = Sprint
    fields = ['sprint_days', 'start_date', 'num_dev']
    
class SprintUpdateView(UpdateView):
    model = Sprint
    fields = ['sprint_days', 'start_date', 'num_dev']
    template_name_suffix = '_edit'

class SprintDeleteView(DeleteView):
    model = Sprint
    success_url = reverse_lazy('backlog:settings')

backlog/templates/backlog/detail.html
{% extends "base.html" %}

{% comment %}
    VIEW                TEMPLATE                    	URL PATTERN
    --------------------------------------------------------------------
    DetailView           detail.html                  	/backlog/<id>
{% endcomment %}

{% block title %}Project Huddle - {{ object.title }} {% endblock %}

{% block content %}

	<h2>{{ object.title }}</h2>
	
	<p> <b>Description:</b> {{ object.description }} </p>

	<p> <b>Validation:</b> {{ object.validation }} </p>
				
	<p><b>Value:</b> {{ object.value }} <b>Effort:</b> {{ object.effort }} </p>
					
	<p><b>Submitted by:</b> {{ object.submitted_by }} </p>
	<p><b>Assigned to:</b> {{ object.assigned_to }} </p>
				
	<br />
					
					
	{% if time_records %}
		<table border=1>
			<tr><th>Day</th> <th>Estimated Hours</th> <th>Actual Hours</th></tr>
			{% for rec in time_records %}
			<tr>
				<td>{{ rec.day }}</td>
				<td>{{ rec.estimated_time }}</td>
				<td>{{ rec.actual_time }}</td>
			</tr>
			{% endfor %}
		</table>
	{% else %}
		<p>No time records available.  </p>
	{% endif %}
	<a href="{% url 'backlog:time_record_add' %}">+Add New Time Record</a>
				
{% endblock %}

backlog/templates/backlog/edit_time_record.html
{% extends "base.html" %}

{% comment %}
    VIEW                TEMPLATE                        URL PATTERN
    --------------------------------------------------------------------
    TimeRecordUpdate    edit_time_record.html           /backlog/time/edit/<id>
{% endcomment %}

{% block title %}Project Huddle - Edit Time Record {% endblock %}

{% block content %}

	<h3>Edit Time Record</h3>
	<form action="" method="post">{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Update" />
	</form>
{% endblock %}

backlog/templates/backlog/index.html
{% extends "base.html" %}

{% comment %}
    VIEW                TEMPLATE                    URL PATTERN
    --------------------------------------------------------------------
    IndexView           index.html                  /backlog/
{% endcomment %}

{% block title %}Project Huddle - Backlog {% endblock %}

{% block content %}
	<h2>Backlog</h2>
				
	<a href="{% url 'backlog:userstory_add' %}">+Add New</a>
	
	{% if backlog_list %}
		<table>
		{% for us in backlog_list %}
			<tr>
				<td><a href="{% url 'backlog:detail' us.id %}">{{ us.title }}</a> </td>
				<td><a href="{% url 'backlog:userstory_edit' us.id %}">edit</a> </td>
				<td><a href="{% url 'backlog:userstory_delete' us.id %}">delete</a> </td>
			</tr>
		{% endfor %}
		</table>
	{% else %}
		<p>No User Stories available. </p>
	{% endif %}

{% endblock %}

backlog/templates/backlog/settings.html
{% extends "base.html" %}

{% comment %}
    VIEW                TEMPLATE                    URL PATTERN
    --------------------------------------------------------------------
    SprintDetailView    settings.html               /backlog/settings/<id>/
{% endcomment %}

{% block title %}Project Huddle - settings {% endblock %}

{% block content %}
	<h2>Sprint Information</h2>
	<p>
		<b>Length of sprint:</b> {{ object.sprint_days }}
	</p>

	<p>
		<b>Start Date:</b> {{ object.start_date }}
	</p>
				
	<p>Number of developers: {{ object.num_dev }}</p>
{% endblock %}

backlog/templates/backlog/sprint_confirm_delete.html
{% extends "base.html" %}

{% comment %}
    VIEW                TEMPLATE                    URL PATTERN
    --------------------------------------------------------------------
    SprintDeleteView    sprint_confirm_delete.html  /backlog/delete/<id>
{% endcomment %}

{% block title %}Project Huddle - Confirm Delete {% endblock %}

{% block content %}
	<form action="" method="post">{% csrf_token %}
    	<p>Are you sure you want to delete "{{ object }}"?</p>
    	<input type="submit" value="Confirm" />
	</form>

{% endblock %}

backlog/templates/backlog/sprint_edit.html
{% extends "base.html" %}

{% comment %}
    VIEW                TEMPLATE                    URL PATTERN
    --------------------------------------------------------------------
    SprintUpdateView    sprint_edit.html            /backlog/settings/edit/<id>
{% endcomment %}

{% block title %}Project Huddle - Edit Sprint Settings {% endblock %}

{% block content %}

	<h3>Edit Sprint Settings</h3>
	<form action="" method="post">{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Update" />
	</form>
{% endblock %}

backlog/templates/backlog/sprint_form.html
{% extends "base.html" %}

{% comment %}
    VIEW                TEMPLATE                    URL PATTERN
    --------------------------------------------------------------------
    SprintCreateView    sprint_form.html            /backlog/settings/add/
{% endcomment %}

{% block title %}Project Huddle - Add New Sprint {% endblock %}

{% block content %}
	<h3> Sprint settings</h3>
	<form action="" method="post">{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Submit" />
	</form>

{% endblock %}

backlog/templates/backlog/sprint_list.html
{% extends "base.html" %}

{% comment %}
    VIEW                TEMPLATE                    URL PATTERN
    --------------------------------------------------------------------
    SprintListView      sprint_list.html            /backlog/settings/
{% endcomment %}

{% block title %}Project Huddle - Settings {% endblock %}

{% block content %}
	<h2>Sprint Settings</h2>
				
	{% if sprint_list %}
	
		{% for sprint in sprint_list %}
			<p><a href="{% url 'backlog:view_sprint' sprint.id %}">
				Current sprint begins:  {{ sprint.start_date }} 
				Lasts for {{ sprint.sprint_days }} days</a> 
			(<a href="{% url 'backlog:sprint_edit' sprint.id %}">edit</a>) 
			(<a href="{% url 'backlog:sprint_delete' sprint.id %}">delete</a>)
			</p>
		{% endfor %}
		
	{% else %}
	
		<a href="{% url 'backlog:create_sprint' %}">+Create New Sprint</a>
		
	{% endif %}

{% endblock %}

backlog/templates/backlog/timerecord_confim_delete.html
{% extends "base.html" %}

{% comment %}
    VIEW                TEMPLATE                        URL PATTERN
    --------------------------------------------------------------------
    TimeRecordDelete    timerecord_confirm_delete.html  /backlog/time/delete/<id>
{% endcomment %}

{% block title %}Project Huddle - Confirm Delete {% endblock %}

{% block content %}
	<form action="" method="post">{% csrf_token %}
    	<p>Are you sure you want to delete "{{ object }}"?</p>
    	<input type="submit" value="Confirm" />
	</form>

{% endblock %}

backlog/templates/backlog/timerecord_form.html
{% extends "base.html" %}

{% comment %}
    VIEW                TEMPLATE                        URL PATTERN
    --------------------------------------------------------------------
    TimeRecordCreate    timerecord_form.html            /backlog/time/add/
{% endcomment %}

{% block title %}Project Huddle - Create Time Record {% endblock %}

{% block content %}

	<h3>Create Time Record</h3>
	
	<form action="" method="post">{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Create" />
	</form>
	
{% endblock %}

backlog/templates/backlog/timerecords_list.html
{% extends "base.html" %}

{% comment %}
    VIEW                TEMPLATE                        URL PATTERN
    --------------------------------------------------------------------
    TimeRecordList      timerecords_list.html           /backlog/time/
{% endcomment %}

{% block title %}Project Huddle - Time Records {% endblock %}

{% block content %}
	<h2>  All Time Records </h2>
				
	<a href="{% url 'backlog:time_record_add' %}">+Add New</a>
	
	{% if time_records %}
	
		<table>
		{% for rec in time_records %}
			<tr>
			<td><a href="{% url 'backlog:time_record' rec.id %}">{{ rec.day }}</a> </td>
			<td><a href="{% url 'backlog:time_record_edit' rec.id %}">edit</a> </td>
			<td><a href="{% url 'backlog:time_record_delete' rec.id %}">delete</a> </td>
			</tr>
		{% endfor %}
		</table>
		
	{% else %}
	
		<p>No records available. </p>
		
	{% endif %}

{% endblock %}

backlog/templates/backlog/userstory_confirm_delete.html
{% extends "base.html" %}

{% comment %}
    VIEW                TEMPLATE                    	URL PATTERN
    --------------------------------------------------------------------
    UserStoryDelete     userstory_confirm_delete.html   /backlog/delete/<id>
{% endcomment %}

{% block title %}Project Huddle - Confirm Delete {% endblock %}

{% block content %}
	<form action="" method="post">{% csrf_token %}
    	<p>Are you sure you want to delete "{{ object }}"?</p>
    	<input type="submit" value="Confirm" />
	</form>

{% endblock %}

backlog/templates/backlog/userstory_edit.html
{% extends "base.html" %}

{% comment %}
    VIEW                TEMPLATE                    	URL PATTERN
    --------------------------------------------------------------------
    UserStoryUpdate     userstory_edit.html             /backlog/edit/<id>
{% endcomment %}


{% block title %}Project Huddle - Edit User Story {% endblock %}

{% block content %}

	<h3>Edit User Story</h3>
		<form action="" method="post">{% csrf_token %}
			{{ form.as_p }}
			<input type="submit" value="Update" />
		</form>
		
{% endblock %}

backlog/templates/backlog/userstory_form.html
{% extends "base.html" %}

{% comment %}
    VIEW                TEMPLATE                    	URL PATTERN
    --------------------------------------------------------------------
    UserStoryCreate     userstory_form.html             /backlog/add/
{% endcomment %}


{% block title %}Project Huddle - Create User Story {% endblock %}

{% block content %}

	<h3>Create User Story</h3>
	<form action="" method="post">{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Create" />
	</form>
{% endblock %}